name: import_convertor
description: A CLI program to convert package imports to path imports in Dart projects.
version: 1.0.0
homepage: https://github.com/buraktabn/import_converter
repository: https://github.com/buraktabn/import_converter
issue_tracker: https://github.com/buraktabn/import_converter/issues
documentation: https://github.com/buraktabn/import_converter/blob/main/README.md

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
